services:
  - type: web
    name: gregory-robert-portfolio
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 20
